"""
Concept: PostgreSQL checkpointer for durable LangGraph state.

In production, MemorySaver is NOT acceptable:
  - Data lost on server restart
  - Not shared across multiple FastAPI instances
  - Cannot support time-travel or compliance requirements

AsyncPostgresSaver writes a checkpoint row after every graph node:
  table: checkpoints
    thread_id    TEXT     ← identifies the conversation
    checkpoint_id UUID    ← unique per node execution
    parent_id    UUID     ← links to previous checkpoint (forms a tree)
    checkpoint   JSONB    ← serialised state (messages, context, etc.)
    metadata     JSONB    ← node name, run_id, etc.
    created_at   TIMESTAMPTZ

This enables:
  - Durable multi-turn conversations across restarts
  - Horizontal scaling (any server can resume any thread)
  - Time-travel: replay from any past checkpoint
  - HITL: graph pauses, state is safe until the user approves

Run:
    python 15_production_architecture/03_postgres_checkpointer.py
"""


def section(title: str) -> None:
    print(f"\n{'='*70}")
    print(f"  {title}")
    print('='*70)


# ═══════════════════════════════════════════════════════════════════════════════
section("1. Database schema (created by checkpointer.setup())")
# ═══════════════════════════════════════════════════════════════════════════════
print("""
  AsyncPostgresSaver.setup() creates these tables automatically:

  CREATE TABLE IF NOT EXISTS checkpoints (
      thread_id      TEXT        NOT NULL,
      checkpoint_ns  TEXT        NOT NULL DEFAULT '',
      checkpoint_id  UUID        NOT NULL,
      parent_id      UUID,
      type           TEXT,
      checkpoint     JSONB       NOT NULL,
      metadata       JSONB       NOT NULL DEFAULT '{}',
      PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
  );

  CREATE TABLE IF NOT EXISTS checkpoint_writes (
      thread_id      TEXT        NOT NULL,
      checkpoint_ns  TEXT        NOT NULL DEFAULT '',
      checkpoint_id  UUID        NOT NULL,
      task_id        UUID        NOT NULL,
      idx            INTEGER     NOT NULL,
      channel        TEXT        NOT NULL,
      type           TEXT,
      value          JSONB,
      PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
  );

  checkpoint_writes holds in-progress node outputs before they are
  committed as a full checkpoint — this is the durability mechanism.
""")


# ═══════════════════════════════════════════════════════════════════════════════
section("2. Setting up the checkpointer in FastAPI")
# ═══════════════════════════════════════════════════════════════════════════════
print('''
  import os
  from contextlib import asynccontextmanager
  from fastapi import FastAPI
  from psycopg_pool import AsyncConnectionPool
  from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver

  pool: AsyncConnectionPool | None = None

  @asynccontextmanager
  async def lifespan(api: FastAPI):
      global pool

      # POSTGRES_URL format:
      #   postgresql+psycopg://user:password@host:5432/dbname
      pool = AsyncConnectionPool(
          conninfo=os.environ["POSTGRES_URL"],
          min_size=2,     # always keep 2 warm connections
          max_size=10,    # burst up to 10 under load
          open=False,
      )
      await pool.open()

      checkpointer = AsyncPostgresSaver(pool)
      await checkpointer.setup()  # idempotent — safe to call on every start

      # Compile the graph with the persistent checkpointer
      app_graph = build_and_compile_graph(checkpointer)

      yield  # FastAPI serves requests here

      await pool.close()

  api = FastAPI(lifespan=lifespan)
''')


# ═══════════════════════════════════════════════════════════════════════════════
section("3. Using the checkpointer in a request")
# ═══════════════════════════════════════════════════════════════════════════════
print('''
  # thread_id is generated by the client (browser) once per conversation.
  # Pass it in the LangGraph config on every request.

  config = {"configurable": {"thread_id": "conv-user42-20260601"}}

  # Turn 1: graph starts fresh, writes first checkpoint after each node
  result = await app_graph.ainvoke(
      {"messages": [HumanMessage(content="Search Jira for login bugs")]},
      config=config,
  )
  print(result["messages"][-1].content)
  # "I found 3 Jira tickets for login bugs: PROJ-101, PROJ-102, PROJ-103."

  # Turn 2: graph reads the checkpoint, sees previous messages, continues
  result = await app_graph.ainvoke(
      {"messages": [HumanMessage(content="Create a ticket for the first one")]},
      config=config,
  )
  # The graph remembers PROJ-101 from the previous turn
  print(result["messages"][-1].content)
  # "I\'ve created a follow-up ticket PROJ-201 linked to PROJ-101."
''')


# ═══════════════════════════════════════════════════════════════════════════════
section("4. Time-travel: inspect or replay from past state")
# ═══════════════════════════════════════════════════════════════════════════════
print('''
  config = {"configurable": {"thread_id": "conv-user42-20260601"}}

  # List all checkpoints for a thread (most recent first)
  async for checkpoint in app_graph.aget_state_history(config):
      print(f"  checkpoint_id={checkpoint.config['configurable']['checkpoint_id']}")
      print(f"  node_name    ={checkpoint.metadata.get('source', '?')}")
      print(f"  message_count={len(checkpoint.values.get('messages', []))}")
      print()

  # Replay from a specific past checkpoint
  past_config = {
      "configurable": {
          "thread_id":     "conv-user42-20260601",
          "checkpoint_id": "uuid-of-past-checkpoint",
      }
  }
  past_state = await app_graph.aget_state(past_config)
  print("State at that point:", past_state.values)

  # Branch: continue from a past point with a different message
  branch_result = await app_graph.ainvoke(
      {"messages": [HumanMessage(content="Actually, what about PROJ-102 instead?")]},
      config=past_config,
  )
  # Creates a new branch in the checkpoint tree; original history preserved
''')


# ═══════════════════════════════════════════════════════════════════════════════
section("5. Checkpoint lifecycle for a HITL conversation")
# ═══════════════════════════════════════════════════════════════════════════════
print("""
  Thread "conv-T1" checkpoints written over time:

  checkpoint_id | node             | messages | notes
  ──────────────┼──────────────────┼──────────┼───────────────────────────
  chk-001       | __start__        | 1        | HumanMessage saved
  chk-002       | llm_node         | 2        | AIMessage with tool_calls
  ── GRAPH PAUSED (interrupt_before=["tools"]) ──────────────────────────
  ... user sees approval dialog, waits 10 minutes ...
  ── User approves, POST /chat/approve ─────────────────────────────────
  chk-003       | tools            | 4        | 2 ToolMessages added
  chk-004       | llm_node (final) | 5        | Final AIMessage

  At any point between chk-002 and chk-003, a server restart is safe.
  On restart, AsyncPostgresSaver reads from PostgreSQL; no state is lost.
""")


# ═══════════════════════════════════════════════════════════════════════════════
section("6. Local development with SQLite (no PostgreSQL needed)")
# ═══════════════════════════════════════════════════════════════════════════════
print('''
  For local development without a PostgreSQL instance:

  from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver

  async with AsyncSqliteSaver.from_conn_string("checkpoints.db") as checkpointer:
      await checkpointer.setup()
      app_graph = build_and_compile_graph(checkpointer)

      result = await app_graph.ainvoke(
          {"messages": [HumanMessage(content="Hello")]},
          config={"configurable": {"thread_id": "local-test"}},
      )

  # checkpoints.db is a local file — persistent across restarts
  # Switch to AsyncPostgresSaver in staging/production

  # .env.local:
  #   DATABASE_TYPE=sqlite
  #   DATABASE_URL=checkpoints.db

  # .env.production:
  #   DATABASE_TYPE=postgres
  #   POSTGRES_URL=postgresql+psycopg://user:pass@db:5432/app
''')


# ═══════════════════════════════════════════════════════════════════════════════
section("7. pgvector: same PostgreSQL instance for RAG")
# ═══════════════════════════════════════════════════════════════════════════════
print('''
  # Install pgvector extension once:
  #   CREATE EXTENSION IF NOT EXISTS vector;

  # Create embeddings table:
  #   CREATE TABLE documents (
  #       id        SERIAL PRIMARY KEY,
  #       content   TEXT,
  #       embedding vector(1536),   -- text-embedding-3-small dimension
  #       metadata  JSONB
  #   );
  #   CREATE INDEX ON documents USING ivfflat (embedding vector_cosine_ops);

  from langchain_community.vectorstores import PGVector
  from langchain_openai import OpenAIEmbeddings

  vectorstore = PGVector(
      collection_name = "devops_docs",
      connection_string = os.environ["POSTGRES_URL"],
      embedding_function = OpenAIEmbeddings(model="text-embedding-3-small"),
  )

  # Add documents
  vectorstore.add_documents(docs)

  # Search
  results = vectorstore.similarity_search("Kubernetes pod restarts", k=4)

  # One Postgres instance handles:
  #   - LangGraph checkpoints (chat state, HITL pauses, time-travel)
  #   - pgvector embeddings  (RAG retrieval)
  #   - User data            (accounts, preferences)
  # Fewer moving parts = simpler infra, easier backups, one connection pool.
''')
